# Generated by Django 4.2 on 2023-07-14 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='online_zapis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='ФИО')),
                ('phone_number', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator('^\\+375\\d{9}$', message='Phone number must be in format +375XXXXXXXXX')], verbose_name='Телефон')),
                ('place', models.CharField(default='', max_length=100, verbose_name='Адрес')),
                ('date', models.DateField(blank=True, choices=[('2023-07-14', '2023-07-14'), ('2023-07-15', '2023-07-15'), ('2023-07-16', '2023-07-16'), ('2023-07-17', '2023-07-17')], null=True, verbose_name='Дата')),
                ('time', models.CharField(choices=[('', 'Выберите время'), ('09:00', '09:00'), ('10:30', '10:30'), ('12:00', '12:00'), ('13:30', '13:30'), ('15:00', '15:00'), ('16:30', '16:30'), ('18:00', '18:00'), ('19:30', '19:30'), ('21:00', '21:00'), ('22:30', '22:30')], max_length=5, verbose_name='Время')),
                ('main_text', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Онлайн запись',
                'verbose_name_plural': 'Онлайн записи',
            },
        ),
    ]
