# Generated by Django 4.2 on 2023-07-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online_zapis',
            name='date',
            field=models.CharField(choices=[('2023-07-14', '2023-07-14'), ('2023-07-15', '2023-07-15'), ('2023-07-16', '2023-07-16'), ('2023-07-17', '2023-07-17')], default='', max_length=10, verbose_name='Дата'),
        ),
    ]
