# Generated by Django 4.2 on 2023-07-25 15:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0006_alter_online_zapis_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online_zapis',
            name='date',
            field=models.DateField(choices=[(datetime.date(2023, 7, 25), '2023-07-25'), (datetime.date(2023, 7, 26), '2023-07-26'), (datetime.date(2023, 7, 27), '2023-07-27'), (datetime.date(2023, 7, 28), '2023-07-28')], default='', max_length=10, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='online_zapis',
            name='phone_number',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator('^\\+375\\d{9}$', message='Номер телефона должен быть введен в формате: +375XXXXXXXXX')], verbose_name='Телефон'),
        ),
    ]
